# Generated by Django 2.0 on 2020-06-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
    ]
