# Generated by Django 2.0 on 2020-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_order_ordered_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordereditems',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
