# Generated by Django 2.0 on 2020-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_order_ordereditems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordereditems',
        ),
    ]
